import React, {Component} from 'react';
import PushNotification from 'react-native-push-notification';
import AsyncStorage from '@react-native-community/async-storage';
import OneSignal from 'react-native-onesignal'; // Import package from node modules

export default class PushController extends Component {
  // constructor(properties) {
  //   super(properties);
  //   OneSignal.init('afb689c3-a7d0-4664-b74c-cc4ac1652e9b');

  //   OneSignal.addEventListener('received', this.onReceived);
  //   OneSignal.addEventListener('opened', this.onOpened);
  //   OneSignal.addEventListener('ids', this.onIds);
  // }

  // componentWillUnmount() {
  //   OneSignal.removeEventListener('received', this.onReceived);
  //   OneSignal.removeEventListener('opened', this.onOpened);
  //   OneSignal.removeEventListener('ids', this.onIds);
  // }

  // onReceived(notification) {
  //   console.log('Notification received: ', notification);
  // }

  // onOpened(openResult) {
  //   console.log('Message: ', openResult.notification.payload.body);
  //   console.log('Data: ', openResult.notification.payload.additionalData);
  //   console.log('isActive: ', openResult.notification.isAppInFocus);
  //   console.log('openResult: ', openResult);
  // }

  // onIds(device) {
  //   console.log('Device info: ', device);
  // }

  componentDidMount() {
    PushNotification.configure({
      onRegister: async token => {
        console.log({token});
        await AsyncStorage.setItem('fcmToken', token.token);
        PushNotification.subscribeToTopic('Test');
      },
      onNotification: notification => {
        console.log('NOTIFICATION:', notification);

        // process the notification
        ShowNotification();
        // required on iOS only (see fetchCompletionHandler docs: https://github.com/react-native-community/react-native-push-notification-ios)
        // notification.finish(PushNotificationIOS.FetchResult.NoData);
      },
      permissions: {
        alert: true,
        badge: true,
        sound: true,
      },
      senderID: '311307586081',
      requestPermissions: true,
      popInitialNotification: true,
    });

    const ShowNotification = () => {
      PushNotification.localNotification({
        /* Android Only Properties */
        id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
        ticker: 'Pesan baru.', // (optional)
        autoCancel: true, // (optional) default: true
        largeIcon: 'ic_launcher', // (optional) default: "ic_launcher"
        smallIcon: 'ic_notification', // (optional) default: "ic_notification" with fallback for "ic_launcher"
        bigText: 'Anda memiliki pesan baru.', // (optional) default: "message" prop
        subText: null, // (optional) default: none
        color: 'black', // (optional) default: system default
        vibrate: true, // (optional) default: true
        vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
        group: 'siadumjak3', // (optional) add group to message
        ongoing: false, // (optional) set whether this is an "ongoing" notification
        priority: 'high', // (optional) set notification priority, default: high
        visibility: 'private', // (optional) set notification visibility, default: private
        importance: 'high', // (optional) set notification importance, default: high

        /* iOS and Android properties */
        message: 'Anda memiliki pesan baru.', // (required)
        playSound: true, // (optional) default: true
      });
    };
  }

  componentWillUnmount() {
    PushNotification.unregister();
  }

  render() {
    return null;
  }
}
